version: 2.1

workflows:
  version: 2.1
  build-test:
    jobs:
      - build-test:
          context:
            Kwetter

jobs: 
  build-test:
    working_directory: ~/kwetter-frontend

    docker:
      - image: circleci/node:8-browsers

    steps:
      - checkout

      - restore_cache:
          key: kwetter-frontend-{{ .Branch }}-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          paths:
            - ~/"node_modules"
          key: kwetter-frontend-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: Linting
          command: npm run lint

      - run:
          name: Testing
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless

      - run:
          name: Sonarqube
          command: |
            sonar-scanner \ 
              -D"sonar.projectKey=RikvanSpreuwel_JEA6-Kwetter-frontend" 
              -D"sonar.organization=rikvanspreuwel-github" -D"sonar.sources=." 
              -D"sonar.host.url=https://sonarcloud.io" 
              -D"sonar.login=$SONAR_LOGIN_BACKEND"
              
      - store_test_results:
          path: junit
      - store_artifacts:
          path: junit

      - run:
          name: building
          command: npm run build
