version: 2.1

workflows:
  version: 2.1
  build-test:
    jobs:
      - checkout

      - dependencies:
          requires:
            - checkout
      
      - build:
          requires:
            - dependencies
      
      - lint:
          requires:
            - build

      - test:
          requires:
            - build
      
      - sonarqube:
          requires:
            - build
          context:
            Kwetter


executors:
  node:
    docker:
      - image: circleci/node:8-browsers


commands:
  persist_kwetter_workspace:
    steps:
      - persist_to_workspace:
          root: .
          paths: .
  
  attach_kwetter_workspace:
    steps:
      - attach_workspace:
          at: .

  restore_cache_dependencies:
    steps:
      - restore_cache:
          keys: 
            - kwetter-frontend-{{ checksum "package.json" }}
            - kwetter-frontend-

jobs: 
  checkout:
    executor: node
    steps:
      - checkout
      - persist_kwetter_workspace
  
  dependencies:
    executor: node
    steps: 
      - attach_kwetter_workspace
      - restore_cache_dependencies

      - run: ls
      - run: npm install
      
      - save_cache:
          key: kwetter-frontend-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: ls

  build:
    executor: node
    steps:
      - attach_kwetter_workspace
      - restore_cache_dependencies

      - run: cd.. && ls
      - run:
          name: building
          command: ls && npm run build

      - persist_kwetter_workspace
  
  lint:
    executor: node
    steps:
      - attach_kwetter_workspace
      - restore_cache_dependencies

      - run:
          name: Linting
          command: npm run lint

  test:
    executor: node
    steps:
      - attach_kwetter_workspace
      - restore_cache_dependencies

      - run:
          name: Testing
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless

      - store_test_results:
          path: junit

  sonarqube:
    executor: node
    steps:
      - attach_kwetter_workspace
      - restore_cache_dependencies

      - run:
          name: Install Sonarqube
          command: sudo npm install -g sonarqube-scanner

      - run:
          name: Run Sonarqube
          command: sonar-scanner -D"sonar.projectKey=RikvanSpreuwel_JEA6-Kwetter-frontend" -D"sonar.organization=rikvanspreuwel-github" -D"sonar.sources=." -D"sonar.host.url=https://sonarcloud.io" -D"sonar.login=$SONAR_LOGIN_BACKEND"




  # build-test:
  #   working_directory: ~/kwetter-frontend
  #   executor: node
    

  #   steps:

      # - restore_cache:
      #     key: kwetter-frontend-{{ .Branch }}-{{ checksum "package.json" }}

      # - run: npm install

      # - save_cache:
      #     paths:
      #       - ~/"node_modules"
      #     key: kwetter-frontend-{{ .Branch }}-{{ checksum "package.json" }}

      # - run:
      #     name: Linting
      #     command: npm run lint

      # - run:
      #     name: Testing
      #     command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
      
      # - store_test_results:
      #     path: junit
      # - store_artifacts:
      #     path: junit 

      # - run:
      #     name: Install Sonarqube
      #     command: sudo npm install -g sonarqube-scanner

      # - run:
      #     name: Run Sonarqube
      #     command: sonar-scanner -D"sonar.projectKey=RikvanSpreuwel_JEA6-Kwetter-frontend" -D"sonar.organization=rikvanspreuwel-github" -D"sonar.sources=." -D"sonar.host.url=https://sonarcloud.io" -D"sonar.login=$SONAR_LOGIN_BACKEND"

      # - run:
      #     name: building
      #     command: npm run build
