version: 2.1

workflows:
  version: 2.1
  build-test:
    jobs:
      - checkout

      - dependencies:
          requires:
            - checkout
      
      - build:
          requires:
            - dependencies
      
      - lint:
          requires:
            - build

      - test:
          requires:
            - build
      
      - sonarqube:
          requires:
            - build
          context:
            Kwetter

      - approve-dockerhub-publish:
          type: approval
          requires:
            - sonarqube
            - lint
            - test

      - publish-latest-dockerhub:
          filters:
            branches:
              only:
                  - master
                  - release
                  - develop
          requires:
            - approve-dockerhub-publish
          context:
            Kwetter

      - publish-version-dockerhub:
          filters:
            branches:
              only:
                  - master
                  - release
                  - develop
          requires:
            - approve-dockerhub-publish
          context:
            Kwetter


executors:
  node:
    docker:
      - image: circleci/node:8-browsers


commands:
  persist_kwetter_workspace:
    steps:
      - persist_to_workspace:
          root: .
          paths: .
  
  attach_kwetter_workspace:
    steps:
      - attach_workspace:
          at: .

  restore_cache_dependencies:
    steps:
      - restore_cache:
          keys: 
            - kwetter-frontend-{{ .BuildNum }}-{{ checksum "package.json" }}
            - kwetter-frontend-

  publish_latest_to_dockerhub:
    steps:      
      - run:
          name: Docker login
          command: docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

      - run:
          name: Docker build image latest
          command: docker build -t "${DOCKER_USERNAME}"/kwetter-frontend:"${CIRCLE_BRANCH}":latest .

      - run:
          name: Docker push image latest
          command: docker push "${DOCKER_USERNAME}"/kwetter-frontend:"${CIRCLE_BRANCH}":latest
    
  publish_with_version_to_dockerhub:
    steps:
      - run:
          name: Set version environment variable
          command: echo 'export VERSION=$(npm run version --silent)' >> $BASH_ENV

      - run:
          name: Docker login
          command: docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

      - run:
          name: Docker build image with version
          command: docker build -t "${DOCKER_USERNAME}"/kwetter-frontend:"${CIRCLE_BRANCH}"-"${VERSION}" .

      - run:
          name: Docker push image with version
          command: docker push "${DOCKER_USERNAME}"/kwetter-frontend:"${CIRCLE_BRANCH}"-"${VERSION}"
              
jobs: 
  checkout:
    executor: node
    steps:
      - checkout
      - persist_kwetter_workspace
  
  dependencies:
    executor: node
    steps: 
      - attach_kwetter_workspace
      - restore_cache_dependencies

      - run: ls
      - run: npm install
      
      - save_cache:
          key: kwetter-frontend-{{ .BuildNum }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: ls

  build:
    executor: node
    steps:
      - attach_kwetter_workspace
      - restore_cache_dependencies

      - run:
          name: building
          command: ls && npm run build

      - persist_kwetter_workspace
  
  lint:
    executor: node
    steps:
      - attach_kwetter_workspace
      - restore_cache_dependencies

      - run:
          name: Linting
          command: npm run lint

  test:
    executor: node
    steps:
      - attach_kwetter_workspace
      - restore_cache_dependencies

      - run:
          name: Testing
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless

      - store_test_results:
          path: junit

  sonarqube:
    executor: node
    steps:
      - attach_kwetter_workspace
      - restore_cache_dependencies

      - run:
          name: Install Sonarqube
          command: sudo npm install -g sonarqube-scanner

      - run:
          name: Run Sonarqube
          command: sonar-scanner -D"sonar.projectKey=RikvanSpreuwel_JEA6-Kwetter-frontend" -D"sonar.organization=rikvanspreuwel-github" -D"sonar.sources=." -D"sonar.host.url=https://sonarcloud.io" -D"sonar.login=$SONAR_LOGIN_BACKEND"

  publish-version-dockerhub:
    machine: true
    steps:
      - attach_kwetter_workspace
      - restore_cache_dependencies
      - publish_with_version_to_dockerhub

  publish-latest-dockerhub:
    machine: true
    steps:
      - attach_kwetter_workspace
      - restore_cache_dependencies
      - publish_latest_to_dockerhub